import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import DarkBackground from "@/component/bg";
import ChatWidget from "@/component/chatbox";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Bonitaa Hair Clinic",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logos.webp", sizes: "any", type: "image/webp" },
      { url: "/logos.webp", sizes: "16x16", type: "image/webp" },
      { url: "/logos.webp", sizes: "32x32", type: "image/webp" },
    ],
    apple: [{ url: "/logos.webp", sizes: "180x180", type: "image/webp" }],
    other: [
      { rel: "icon", url: "/logos.webp", sizes: "192x192", type: "image/webp" },
      { rel: "icon", url: "/logos.webp", sizes: "512x512", type: "image/webp" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <DarkBackground />
        <ChatWidget />
        {children}
      </body>
    </html>
  );
}