import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Script from "next/script"; // ✅ add this
import "./globals.css";
import DarkBackground from "@/component/bg";
import ChatWidget from "@/component/chatbox";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Bonitaa Hair Clinic",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logos.webp", sizes: "any", type: "image/webp" },
      { url: "/logos.webp", sizes: "16x16", type: "image/webp" },
      { url: "/logos.webp", sizes: "32x32", type: "image/webp" },
    ],
    apple: [{ url: "/logos.webp", sizes: "180x180", type: "image/webp" }],
    other: [
      { rel: "icon", url: "/logos.webp", sizes: "192x192", type: "image/webp" },
      { rel: "icon", url: "/logos.webp", sizes: "512x512", type: "image/webp" },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>

        {/* ✅ Google Ads Tag */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-16555631657"
          strategy="afterInteractive"
        />
        <Script id="google-ads" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-16555631657');
          `}
        </Script>

        <DarkBackground />
        <ChatWidget />
        {children}
      </body>
    </html>
  );
}